---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.setvars.outputs.tag }}
      branch: ${{ steps.setvars.outputs.branch }}
    steps:
      - name: Set vars
        id: setvars
        run: |
          echo ::set-output name=tag::${{github.ref}#refs/}
          echo ::set-output name=branch::${{github.base_ref}}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          mkdir dist
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            name: 'test'
            compress: true
            dest: 'dist'
            ldflags: "-X github.com/SalaciousSystems/studious-rotary-phone/internal/app.buildVersion={{needs.init.outputs.tag}} -X github.com/SalaciousSystems/studious-rotary-phone/internal/app.buildBranch={{needs.init.outputs.branch}}"

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*
